# Generated by Django 2.2.24 on 2021-08-01 12:16

import core.db.models
from django.db import migrations, models
import django.db.models.deletion
import libs.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ugc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ugc_id', core.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='用户id')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_user.User', to_field='user_id', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '动态表',
                'db_table': 't_ugc',
            },
        ),
    ]
